"""household table

Revision ID: cf74279ade62
Revises: 
Create Date: 2021-07-07 17:26:52.890958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf74279ade62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_hold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_first_name', sa.String(length=64), nullable=True),
    sa.Column('major_last_name', sa.String(length=64), nullable=True),
    sa.Column('major_id', sa.String(length=64), nullable=True),
    sa.Column('major_phone', sa.String(length=64), nullable=True),
    sa.Column('major_birth_year', sa.String(length=64), nullable=True),
    sa.Column('minor_first_name', sa.String(length=64), nullable=True),
    sa.Column('minor_last_name', sa.String(length=64), nullable=True),
    sa.Column('minor_id', sa.String(length=64), nullable=True),
    sa.Column('minor_phone', sa.String(length=64), nullable=True),
    sa.Column('address_city', sa.String(length=64), nullable=True),
    sa.Column('address_street', sa.String(length=64), nullable=True),
    sa.Column('address_house_num', sa.String(length=64), nullable=True),
    sa.Column('short_description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_phone'),
    sa.UniqueConstraint('minor_phone')
    )
    op.create_index(op.f('ix_house_hold_major_first_name'), 'house_hold', ['major_first_name'], unique=False)
    op.create_index(op.f('ix_house_hold_major_id'), 'house_hold', ['major_id'], unique=True)
    op.create_index(op.f('ix_house_hold_major_last_name'), 'house_hold', ['major_last_name'], unique=False)
    op.create_index(op.f('ix_house_hold_minor_id'), 'house_hold', ['minor_id'], unique=True)
    op.create_table('intervension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('in_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('therapist', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('txt', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['house_hold.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervension_date'), 'intervension', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervension_date'), table_name='intervension')
    op.drop_table('intervension')
    op.drop_index(op.f('ix_house_hold_minor_id'), table_name='house_hold')
    op.drop_index(op.f('ix_house_hold_major_last_name'), table_name='house_hold')
    op.drop_index(op.f('ix_house_hold_major_id'), table_name='house_hold')
    op.drop_index(op.f('ix_house_hold_major_first_name'), table_name='house_hold')
    op.drop_table('house_hold')
    # ### end Alembic commands ###
